#include"work_que.h"
void que_insert(pque_t pq,pnode_t pnew)//尾插法将请求程插入队列
{
	if(!pq->que_head)
	{
		pq->que_head=pnew;
		pq->que_tail=pnew;
	}
	else{
		pq->que_tail->pNext=pnew;
		pq->que_tail=pnew;
	}
	pq->size++;
}
void  que_get(pque_t pq,pnode_t *pcur)//从队列头调用线程，防止饥饿
{
	*pcur=pq->que_head;
	if(NULL==*pcur)
	{
		return;
	}
	if(-1==(*pcur)->new_fd)//如果是标志节点，解锁退出
	{
		pthread_mutex_unlock(&pq->que_mutex);
		pthread_exit(NULL);
	}
	//正常取任务
	pq->que_head=pq->que_head->pNext;
	if(pq->que_head==NULL)
	{
		pq->que_tail=NULL;
	}
	pq->size--;
}
void que_insert_exit(pque_t pq,pnode_t pnew)//插入标志结束的节点
{
	if(NULL==pq->que_head)
	{
		pq->que_head=pnew;
		pq->que_tail=pnew;
	}else
	{
		pnew->pNext=pq->que_head;
		pq->que_head=pnew;
	}
	pq->size++;
}
